version: "3"

services:
  graphdb:
    container_name: graphdb
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        version: 10.1.3
    restart: unless-stopped
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx20g -Xms20g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=600
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports: 
      - 7200:7200
    volumes:
      - ./data:/opt/graphdb/home
